---
# Spring
spring:
  application:
    name: resource-ms
  profiles:
    active: local
  # Spring Data Rest
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true
      default-media-type: application/hal+json
  # JSON Pretty Print
  jackson:
    serialization:
      indent-output: true
    deserialization:
      accept-empty-array-as-null-object: true
  kafka:
    group-id: "resource"
# Server
server:
  port: 8080
  compression.enabled: true
  compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
# Keycloak
keycloak:
  enabled: true
  realm: archilab
  resource: coalbase-api
  bearer-only: true
  principal-attribute: preferred_username
# Kafka-topic
resource.topic: resource
learning-space.topic: learning-space

