---
spring:
  data:
    mongodb:
      uri: mongodb://${RESOURCE_DB_HOST}:${RESOURCE_DB_PORT}/${RESOURCE_DB_NAME}
  # kafka servers
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
# Keycloak
keycloak:
  auth-server-url: https://login.archi-lab.io/auth/
# CORS
security:
  cors:
    allowed-origins: "https://www.coalbase.archi-lab.io, https://www.coalbase.archi-lab.de, https://coalbase.archi-lab.io, https://coalbase.archi-lab.de"
    allowed-headers: '*'
    allowed-methods: '*'
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/,http://eureka-2:8761/eureka/
