FROM openjdk:8-slim

CMD apt update
CMD apt install -y curl

EXPOSE 8080
COPY target/resource-0.0.1-SNAPSHOT.jar app-resource.jar
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","/app-resource.jar" ]
