version: '3.4'

services:
  mongo:
    image: mongo:4.1
    volumes:
      - resource_db:/data/db
    networks:
      - service_internal
  springboot-service:
    image: docker.nexus.archi-lab.io/archilab/coalbase-resource
    environment:
      - TZ=Europe/Berlin
      - RESOURCE_DB_HOST=mongo
      - RESOURCE_DB_PORT=27017
      - RESOURCE_DB_NAME=resource_db
    depends_on:
      - mongo
    networks:
      - service_internal
      - coalbase_backend
volumes:
  resource_db: {}
networks:
  service_internal:
  coalbase_backend:
    external: true
